export { default as Main } from "./Main";
export { default as NavBar } from "./NavBar";
export { default as Profile } from "./Profile";
export { default as Register } from "./Register";
// export { default as Login } from "./Login";
export { default as Posts } from "./Posts";
export { default as Home } from "./Home";
export { default as NewPost } from "./NewPost";
export { default as ModPost } from "./ModPost";
export { default as Header } from "./Header";
